### ISSUE TITLE
bug？

### ISSUE THREAD

**Issue by lehhair** [ybw2016v/mkcl#2]
root@lehh-virtual-machine:/home/misskey/mkcl# python3 mkcl.py -d 12 -c /home/misskey/.config/default.yml -s 2023-09-14
/home/misskey/mkcl/mkcl.py:32: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  dogy=yaml.load(dogfile)
Traceback (most recent call last):
  File "/home/misskey/mkcl/mkcl.py", line 49, in <module>
    resdoggg=dogclean([dog_db_host,dog_db_port,dog_db_db,dog_db_user,dog_db_pass],[dog_redis_host,dog_redis_port,dog_redis_pass,dog_redis_db],sdog,erydog)
  File "/home/misskey/mkcl/core.py", line 55, in dogclean
    pgdog = psycopg2.connect(database=dogdbi[2], user=dogdbi[3], password=dogdbi[4], host=dogdbi[0], port=dogdbi[1])
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "db" to address: Temporary failure in name resolution

**Comment by lehhair** [comment]
哦，这个问题我解决了，但是运行成功后提示清退0个帖子
